### ISSUE TITLE
Allow running multiple times without affecting already fixed videos

### ISSUE THREAD

**Issue by michaelBenin** [rosszurowski/vanilla-fitvids#2] opened 2016-04-26 16:44 UTC
Hello, awesome lib!

I'm using your library and I've found it fixes videos that have already been fixed.

Would be nice to add a data attribute to check for that. 

Valid feature? Let me know I'll make a PR.

**Comment by rosszurowski** [comment] 2016-04-27 01:03
Hey! Thanks for the interest.

There's currently a check to make sure videos don't get wrapped twice ([relevant line here](https://github.com/rosszurowski/vanilla-fitvids/blob/c0bdf120d339e0e1004572626c40c781fffb66d7/index.js#L56)), so this shouldn't be happening. I just [added a test](https://github.com/rosszurowski/vanilla-fitvids/commit/6504411f594eb1eea1e7a73b14239dd3733ddc25) to confirm, but it seems to be working correctly for me.

Mind posting a test case of where it wraps videos twice? Feel free to send a PR for the test or with a fix if that's easier.

**Comment by michaelBenin** [comment] 2016-04-27 01:57
@rosszurowski it was using a custom player. I'll try to set up a repro tomorrow.

**Comment by rosszurowski** [comment] 2016-05-09 21:19
Tried again with custom players and it worked fine. Closing this out, but feel free to re-open if you can reproduce it.

**Closed by rosszurowski** 2016-05-09 21:19 UTC
